---
title: "Covid91 vaccine study Final2022"
author: "Carmen Ramos-Caminos"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="final_Data.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid91) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.  

Is the new preventative vaccine (covid91) treatment effective for the following subgroups sex (male/female), LGBTQ, DrugUser? 

$H_0$ Preventative covid91 treatment is effective for subgroup: sex (male/female): LGBTQ: DrugUser 

$H_a$ Preventative covid91 treatment is not effective for subgroup: sex (male/female): LGBTQ: DrugUser 

# Methods 

Both treatment and subgroups sex(male/female), LGBTQ, DrugUser are categorical variables. Therefore, the method of analysis technique used is cat~cat. The plot is a plotbar, summary is a crosstable and the inference will be a chi-square test. 


## Males


## Females


## LGBTQ



## Druggies

